sudo: required
services:
  - docker

before_install:
  - docker build -t pculurciello/simple-react -f Dockerfile.dev .

script:
  - docker run pculurciello/simple-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "simple-react"
  env: "SimpleReact-env"
  bucket-name: "elasticbeanstalk-us-east-1-552235802020"
  bucket_pat: "simple-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"